export enum Actions {
  QUERY_PENDING_TRANSACTION_REQUESTS = 'RAMP/QUERY_PENDING_TRANSACTION_REQUESTSj',
  SET_PENDING_TRANSACTION_LISTS = 'RAMP/SET_PENDING_TRANSACTION_LISTS',
  MAKE_DEPOSIT_REQUEST = 'RAMP/MAKE_DEPOSIT_REQUEST',
  MAKE_WITHDRAWAL_REQUEST = 'RAMP/MAKE_WITHDRAWAL_REQUEST',
}
