export enum Actions {
  QUERY_PENDING_TRANSACTION_REQUESTS = 'RAMP/QUERY_PENDING_TRANSACTION_REQUESTSj',
  SET_PENDING_TRANSACTION_LISTS = 'RAMP/SET_PENDING_TRANSACTION_LISTS',
  QUERY_MY_TRANSACTION_REQUESTS = 'RAMP/QUERY_MY_TRANSACTION_REQUESTS',
  SET_MY_TRANSACTION_LISTS = 'RAMP/SET_MY_TRANSACTION_LISTS',
  MAKE_RAMP_EXCHANGE_REQUEST = 'RAMP/MAKE_RAMP_EXCHANGE_REQUEST',
  AGENT_FULFILL_REQUEST = 'RAMP/AGENT_FULFILL_REQUEST',
  APPROVE_TRANSACTION = 'RAMP/APPROVE_TRANSACTION',
  CANCEL_TRANSACTION = 'RAMP/CANCEL_TRANSACTION',

  // Smart contract event.
  TRANSACTION_INIT_CONTRACT_EVENT = 'RAMP/TRANSACTION_INIT_CONTRACT_EVENT',
  AGENT_PAIRING_CONTRACT_EVENT = 'RAMP/AGENT_PAIRING_CONTRACT_EVENT',
  CLIENT_CONFIRMATION_CONTRACT_EVENT = 'RAMP/CLIENT_CONFIRMATION_CONTRACT_EVENT',
  AGENT_CONFIRMATION_CONTRACT_EVENT = 'RAMP/AGENT_CONFIRMATION_CONTRACT_EVENT',
  SAVED_CLIENT_PAYMENT_INFORMATION_CONTRACT_EVENT = 'RAMP/SAVED_CLIENT_PAYMENT_INFORMATION_CONTRACT_EVENT',
  CONFIRMATION_COMPLETE_CONTRACT_EVENT = 'RAMP/CONFIRMATION_COMPLETE_CONTRACT_EVENT',
  TRANSACTION_COMPLETE_CONTRACT_EVENT = 'RAMP/TRANSACTION_COMPLETE_CONTRACT_EVENT',
  TRANSACTION_CANCELED_CONTRACT_EVENT = 'RAMP/TRANSACTION_CANCELED_CONTRACT_EVENT',

  UPDATE_SELECTED_TRANSACTION = 'RAMP/UPDATE_SELECTED_TRANSACTION',
  REFETCH_SELECTED_TRANSACTION = 'RAMP/REFETCH_SELECTED_TRANSACTION',
}
